vim.cmd("set expandtab")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set number")
vim.g.mapleader = " "
vim.keymap.set("n", "<leader>nh", ":nohl", {})
vim.keymap.set("n", "<leader>nN", ":set nonumber", {})
vim.keymap.set("n", "<leader>N", ":set number", {})
vim.keymap.set("n", "<leader>S", ":w!", {})
vim.keymap.set("n", "<leader>Sa", ":wa!", {})
